# Site settings
title: Nikhil Kumar Blog
email: nikhil.kumar707128@gmail.com
description: "Excerpts from SachAI of my life."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nikhil-xb.github.io" 
twitter_username: nikhil__xb
github_username:  nikhil-xb

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown: 
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
