# Site settings
title: Nikhil Kumar Blog
email: nikhil.kumar707128@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Excerpts from SachAI of my life
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.nikhil-xb.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nikhil__xb
github_username:  nikhil-xb

# Build settings
theme: minima
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown: 
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
